services:
  - type: web
    name: growcommon
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_ENV_VALIDATION
        value: "true"


